apps/usuarios/urls.py
from django.conf.urls import url, include
from views import RegistroUsuario,UserHome, UserHomeErr, update_profile, Creditos, Creditos1, Simulador1,Simulador2,Simulador3,Simulador4,Simulador5,Simulador6,Simulador7, Metodologia,Metodologia1,Condiciones
from django.contrib.auth.decorators import login_required

urlpatterns = [
    #url(r'^registrar/', RegistroUsuario.as_view(), name="registrar"),
    url(r'^registrar/', RegistroUsuario, name="registrar"),
    url(r'^creditos/', Creditos, name="creditos"),
    url(r'^creditos1/', Creditos1, name="creditos1"),
    url(r'^$', login_required(UserHome), name="usuarios_home"),
    url(r'^(?P<errorMsg>\d+)/$', login_required(UserHomeErr), name="usuarios_home_err"),
    url(r'^misdatos/', login_required(update_profile), name="usuarios_datos"),
    url(r'^simulador/1/', Simulador1, name="simulador1"),
    url(r'^simulador/2/', Simulador2, name="simulador2"),
    url(r'^simulador/3/', Simulador3, name="simulador3"),
    url(r'^simulador/4/', Simulador4, name="simulador4"),
    url(r'^simulador/5/', Simulador5, name="simulador5"),
    url(r'^simulador/6/', Simulador6, name="simulador6"),
    url(r'^simulador/7/', Simulador7, name="simulador7"),
    url(r'^metodologia/', Metodologia, name="metodologia"),
    url(r'^metodologia1/', login_required(Metodologia1), name="metodologia1"),
    url(r'^condiciones/', Condiciones, name="condiciones"),
    ]

iarseapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login,password_reset,password_reset_done,password_reset_confirm,password_reset_complete, \
    logout_then_login
from django.contrib.auth.decorators import login_required
from apps.usuarios.views import UserHome


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^usuarios/', include('apps.usuarios.urls',namespace= "usuarios")),
    url(r'^survey/', include('apps.survey.urls',namespace= "surveys")),
    url(r'^reportes/', include('apps.reportes.urls',namespace= "reportes")),
    url(r'^indicadores/', include('apps.indicadores.urls',namespace= "indicadores")),
    url(r'^$', login_required(UserHome), name="land"),
    url(r'^accounts/login/', login,{'template_name':'usuarios/index.html'},name='login'),
    url(r'^logout/', logout_then_login,name="logout"),
    url(r'^reset/password_reset', password_reset,
        {'template_name':'usuarios/password_reset_fm.html',
        'email_template_name': 'usuarios/password_reset_email.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'usuarios/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'usuarios/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'usuarios/password_reset_complete.html'},
        name='password_reset_complete'),

]

apps/usuarios/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Provincia(models.Model):
	name = models.CharField(max_length=400)

	def __str__(self):
		return (self.name)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    empresa = models.CharField(max_length=200, default='')
    empresaCom = models.CharField(max_length=200, default='')
    actividadPrincipal = models.CharField(max_length=200, default='')
    actividadSecundaria = models.CharField(blank=True,null=True,max_length=200, default='')
    email = models.EmailField(default='')
    nombre = models.CharField(max_length=200, default='')
    puesto = models.CharField(max_length=200, default='')
    provincia = models.ForeignKey(Provincia,default=1, null=True)
    localidad= models.CharField(max_length=200, blank=True, default='')
    cp= models.CharField(max_length=200, default='')
    direccion = models.CharField(max_length=500,null=True, blank=True, default='')
    telefono = models.CharField(max_length=50, default='')
    comentarios = models.CharField(blank=True,null=True,max_length=400, default='')
    habilitado = models.BooleanField(default=True)

    def __str__(self):
        return (self.user.username)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

apps/usuarios/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from models import Profile

class RegistroForm (UserCreationForm):

    class Meta:
        model = User
        fields = [
            'username',
        ]
        labels = {
            'username':'CUIT',
        }
        widgets= {
            'username': forms.TextInput(attrs={'type':'number'}),
        }


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
        ]
        labels = {
            'username': 'CUIT',
        }
        widgets = {
            'username': forms.TextInput(attrs={'type': 'number'}),
        }

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('empresa',
                  'empresaCom',
                  'actividadPrincipal',
                  'actividadSecundaria',
                  'cp',
                  'comentarios',
                  'nombre',
                  'email',
                  'puesto',
                  'provincia',
                  'localidad',
                  'direccion',
                  'telefono',
                  )
        labels = {
            'empresa': 'Empresa',
            'empresaCom':'Empresa (Nombre comercial)',
            'actividadPrincipal':'Actividad Principal',
            'actividadSecundaria':'Actividad Secundario',
            'cp':'Codigo Postal',
            'comentarios':'Comentarios Adicionales',
            'nombre':'Nombre completo',
            'email':'E-mail',
            'puesto':'Puesto',
            'provincia':'Provincia',
            'localidad':'Localidad',
            'direccion':'Direccion',
            'telefono':'Telefono',
        }

apps/usuarios/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render

# Create your views here.
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.core.urlresolvers import reverse_lazy
from forms import RegistroForm,ProfileForm, UserForm
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import redirect
from ..survey.models import ResponseMgr
from django.contrib import messages
from ..indicadores.models import Evaluacion
from ..usuarios.models import Profile
from django.core.mail import EmailMessage, EmailMultiAlternatives
from openpyxl import Workbook
from django.http.response import HttpResponse

#class RegistroUsuario(CreateView):
#    model= User
#    template_name= "usuarios/registrar.html"
#    form_class = RegistroForm
#    second_form_class= ProfileForm
#    success_url = reverse_lazy('usuarios:usuarios_home')

def RegistroUsuario(request):
    if request.method == 'POST':
        user_form = RegistroForm(request.POST)
        profile_form = ProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            usuario=user_form.save()
            profile_form = ProfileForm(request.POST, instance=usuario.profile)
            profile=profile_form.save()
            usuario.email=profile.email
            usuario.save()
            html_content = '<p>El usuario <strong>'+usuario.username+' - '+profile.empresa+'</strong> se ha registrado en INDICAGRO.</p>'
            email = EmailMultiAlternatives('Usuario ' + usuario.username + ' creado exitosamente','Este es el mensaje del email',
                                 to=['indicagro@bccba.org.ar'],bcc=['maurimorero@gmail.com'])
            email.attach_alternative(html_content, "text/html")
            email.send()
            print("se mando el email")
            messages.success(request, 'Ya te encuentras habilitado para aplicarte IndicAgro. '
                                      'Gracias por formar parte de un #AgroComprometido!')
            return redirect('usuarios:usuarios_home')
    else:
        user_form = RegistroForm()
        profile_form = ProfileForm()
    return render(request, 'usuarios/registrar.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

def Creditos (request):
    return render(request, 'creditos.html', {})

def Creditos1 (request):
    return render(request, 'creditos1.html', {})

def Metodologia (request):
    return render(request, 'metodologia.html', {})

def Metodologia1 (request):
    return render(request, 'metodologia1.html', {})

def UserHome(request):
    # chequea si el usuario esta habilitado
    mensaje = 0
    perfil = Profile.objects.get(user=request.user)
    if (perfil.habilitado == False):
        mensaje = 1
    pendientes= ResponseMgr.objects.filter(user=request.user,completada=False).order_by('-created')
    evaluaciones = Evaluacion.objects.filter(usuario=request.user).order_by('-fecha')
    indicadoresTodos = Evaluacion.objects.order_by('-fecha')
    perfiles = Profile.objects.all()

    if request.method == 'POST':
        # Creamos el libro de trabajo
        wb = Workbook()

        # Definimos como nuestra hoja de trabajo, la hoja activa, por defecto la primera del libro
        ws = wb.active

        # En la celda B1 ponemos el texto 'REPORTE DE PERSONAS'
        ws['B1'] = 'Reporte de INDICAGRO'

        # Juntamos las celdas desde la B1 hasta la E1, formando una sola celda
        ws.merge_cells('B1:E1')

        # Creamos los encabezados desde la celda B3 hasta la E3
        ws['B3'] = 'Empresa'
        ws['C3'] = 'CUIT'
        ws['D3'] = 'N° BPA'
        cont = 4

        informes = Evaluacion.objects.all().order_by('-fecha')

        # Recorremos el conjunto de personas y vamos escribiendo cada uno de los datos en las celdas
        for informe in informes:
            empresa=Profile.objects.filter(user=informe.usuario)
            ws.cell(row=cont, column=2).value = empresa[0].empresaCom
            ws.cell(row=cont, column=3).value = empresa[0].user.username
            ws.cell(row=cont, column=4).value = informe.id
            cont = cont + 1

        # Establecemos el nombre del archivo
        nombre_archivo = "ReporteIndicagro.xlsx"

        # Definimos que el tipo de respuesta a devolver es un archivo de microsoft excel
        response = HttpResponse(content_type="application/ms-excel")
        contenido = "attachment; filename={0}".format(nombre_archivo)
        response["Content-Disposition"] = contenido
        wb.save(response)
        return response

    contexto = {
        'pendientes': pendientes,
        'evaluaciones':evaluaciones,
        'indicadoresTodos':indicadoresTodos,
        'perfiles':perfiles,
        'mensaje':str(mensaje)
    }
    return render(request,'home.html',contexto)

def UserHomeErr(request,errorMsg):
    # chequea si el usuario esta habilitado
    mensaje = 0
    perfil = Profile.objects.get(user=request.user)
    if (perfil.habilitado == False):
        mensaje = 1
    pendientes= ResponseMgr.objects.filter(user=request.user,completada=False).order_by('-created')
    evaluaciones = Evaluacion.objects.filter(usuario=request.user).order_by('-fecha')
    indicadoresTodos = Evaluacion.objects.order_by('-fecha')
    perfiles = Profile.objects.all()
    contexto = {
        'pendientes': pendientes,
        'evaluaciones': evaluaciones,
        'indicadoresTodos': indicadoresTodos,
        'errorMsg':errorMsg,
        'perfiles': perfiles,
        'mensaje': str(mensaje)
    }
    return render(request,'home.html',contexto)

@login_required
@transaction.atomic
def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            #messages.success(request, _('Your profile was successfully updated!'))
            return redirect('usuarios:usuarios_home')
        #else:
            #messages.error(request, _('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'usuarios/actualizar.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

def Simulador1 (request):
    return render(request, 'simulador/1.html', {})

def Simulador2 (request):
    return render(request, 'simulador/2.html', {})

def Simulador3 (request):
    return render(request, 'simulador/3.html', {})

def Simulador4 (request):
    return render(request, 'simulador/4.html', {})

def Simulador5 (request):
    return render(request, 'simulador/5.html', {})

def Simulador6 (request):
    return render(request, 'simulador/6.html', {})

def Simulador7 (request):
    return render(request, 'simulador/7.html', {})

def Condiciones (request):
    return render(request, 'condiciones.html', {})

def Landing (request):
    return render(request, 'landing.html', {})

templates/usuarios/index.html
{% extends 'base/base.html' %}
{% block javascript %}

<script>
    function errorLogin(){
        alert("{{ form.non_field_errors }}");
    }
</script>
{% endblock %}
{% block header %}
{% endblock %}
{% block content %}
    {% load static %}
    <div id="box3"><img src="{% static 'img/indicadores2.png' %}" width="353px" height="181px"></div>		
<form method="post">
    {% csrf_token %}


    <div id="box2">
	<a href="{% static 'download/libro-indicadores.pdf' %}" style="text-decoration:none;"> <input type="button" value="DESCARGAR LIBRO" class="boton11" style="margin: 0px 0px 10px 400px;"></a>
	<a href="{% url 'usuarios:metodologia' %}" style="text-decoration:none;"> <input type="button" value="GUÍA DE USO" class="boton12" style="margin: 0px 0px 10px 10px;"></a>
	<a href="{% url 'usuarios:simulador1' %}" style="text-decoration:none;"> <input type="button" value="SIMULADOR" class="boton11" style="margin: 0px 0px 10px 10px;"></a>
	<a href="{% url 'usuarios:creditos' %}" style="text-decoration:none;"> <input type="button" value="CRÉDITOS" class="boton12" style="margin: 0px 0px 10px 10px;"></a>
		
	
        <table>
            <tr>
                <td>


        <div id="boxLogin1">
            <table>
                <tr>
                    <td>

                    <div id="texttt" style="width: 320px;margin: 15px 0px 15px 15px;">INDICADORES DE RESPONSABILIDAD SOCIAL<br> Y SUSTENTABILIDAD PARA EL AGRO</div>
                    </td>
                </tr>
                <tr>
                    <td>
                            <input class="form-control" type="text" name="username" placeholder="CUIT (Ingrese sólo números)" style="height:30px;width: 320px;margin: 0px 0px 10px 15px;">
                    </td>
                </tr>
                <tr>
                    <td>
                        <input class="form-control" type="password" name="password"  placeholder="CONTRASEÑA" style="height:30px;width: 320px;margin: 0px 0px 10px 15px;">
                    </td>
                 </tr>
                <tr>
                    <td>
                        <table>
                            <tr>
                                <td align="center">
                                    <a href="{% url 'password_reset' %}" style="margin: 0px 0px 0px 10px;">Olvidé mi contraseña</a>
                                </td>
                                <td>
                                     <button type="submit" class="boton5" style="margin: 0px 0px 0px 80px;">INGRESAR</button>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>

                <tr>
                    <td>
                        <a href="{% url 'usuarios:registrar' %}" style="text-decoration:none;"> <input type="button" value="REGISTRARSE" class="boton10" style="margin: 20px 0px 10px 15px;"></a>
                     </td>
                </tr>


            {% if form.errors %}
                {% for error in form.non_field_errors %}
                    <script>
                       alert("{{ error|escape }}");
                    </script>
                {% endfor %}
            {% endif %}
                </table>
        </div>

            </td>
                <td>
                               <div style="margin-left: 25px;margin-top: -36px;"> <iframe width="511" height="287" src="https://www.youtube.com/embed/cAcsa2Xzs7Q"  allowfullscreen ></iframe></div>
                </td>
            </tr>
        </table>
    </div>
</form>


{% if messages %}
<ul class="messages">
    {% for message in messages %}
        {% if message.tags %}
            <script>
                   alert("{{ message }}");
            </script>
        {% endif %}
    {% endfor %}
</ul>
{% endif %}

<div id="boxLogos">
{% load static %}
<div class="slider">
			<ul>
				<li>

                     <img src="{% static 'img/logosinicio/0.png' %}">
                </li>
				<li>

                    <img src="{% static 'img/logosinicio/1.png' %}">
                </li>
				<li>

                    <img src="{% static 'img/logosinicio/2.png' %}">
                </li>
				<li>

                    <img src="{% static 'img/logosinicio/3.png' %}">
                </li>
				<li>

                     <img src="{% static 'img/logosinicio/0.png' %}">
                </li>
				<li>

                    <img src="{% static 'img/logosinicio/1.png' %}">
                </li>
				<li>

                    <img src="{% static 'img/logosinicio/2.png' %}">
                </li>
			</ul>
		</div>
</div>
{% endblock %}

templates/usuarios/password_reset_fm.html
{% extends 'base/base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <div id="indicagro">
        {% load static %}
        <img src="{% static 'img/indicadores2.png' %}">
    </div>
    <div id="boxLogin">
        <h3>Recuperar contraseña</h3>
        <table>
            <tr>
                <td>
                    <label for="id_email">E-mail:</label></td><td>{{ form.email }}
                </td>
            </tr>
            <tr>
                <td></td>
                <td align="right">
                    <button type="submit" class="boton">Enviar</button>
                </td>
            </tr>
        </table>
    </div>
</form>
{% endblock %}

templates/usuarios/registrar.html
{% extends 'base/base.html' %}
{% block javascript %}


{% endblock %}
{% block content %}
<script type="text/javascript"> 
  function validarCuit(sCUIT) 
	{ 
	    var aMult   = '6789456789'; 
	    var aMult   = aMult.split(''); 
	    var sCUIT   = String(sCUIT); 
	    var iResult = 0; 
	    var aCUIT = sCUIT.split(''); 
	     
	    if (aCUIT.length == 11) 
	    { 
	        // La suma de los productos 
	        for(var i = 0; i <= 9; i++) 
	        { 
	            iResult += aCUIT[i] * aMult[i]; 
	        } 
	        // El módulo de 11 
	        iResult = (iResult % 11); 
	         
	        // Se compara el resultado con el dígito verificador 
	        return (iResult == aCUIT[10]); 
	    }     
	    return false; 
	}  
</script>  		
<script type="text/javascript">
function Guardar(){
    if(document.getElementById('100').checked)
    {	
    	cuit=document.getElementById('id_username').value;
    	if(validarCuit(cuit))
        	document.getElementById("response").submit();
        else
        	alert("Por favor, ingrese un CUIT/CUIL válido (sin guiones ni espacios)");
    }
    else
    {action="/accounts/register/"
        alert("Debe aceptar los términos y condiciones de privacidad para registrarse");
    }
};
</script>
<div id="boxRegistro1">
<form action="/usuarios/registrar/" method="post" id="response">
    {% csrf_token %}

        <table>
            <tr>
                <table align="center">
                        <tr>
                            <td>
                                <h3>REGISTRARSE</h3>
                            </td>
                        </tr>
                </table>
            </tr>
            <tr>
                <table align="center">
                        <tr>
                            <td>
                                {% load static %}
                                <img src="{% static 'img/lineaazul.png' %}" >
                            </td>
                        </tr>
                </table>
            </tr>
            <tr>
                <td>
                    <table>
                        <tr>
                            <td align="left">
                                <div style="margin: 5px 0px 0px 110px;font-size:12px;">Empresa (Razón social)</dir>
                            </td>
                            <td align="left">
                                <div style="margin: 5px 0px 0px 20px;font-size:12px;">Empresa (Nombre comercial)</dir>
                            </td>
                            <td align="left">
                                <div style="margin: 5px 0px 0px 20px;font-size:12px;">CUIT de la empresa(Solo números - login)</dir>
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                               <div style="margin: 0px 0px 5px 110px;font-size:12px;">{{ profile_form.empresa }} {{ profile_form.empresa.errors }}</dir>
                            </td >
                            <td align="left">
                               <div style="margin: 0px 0px 5px 20px;font-size:12px;">{{ profile_form.empresaCom }} {{ profile_form.empresaCom.errors }}</dir>
                            </td>
                            <td align="left">
                                <div style="margin: 0px 0px 5px 20px;font-size:12px;">{{ user_form.username }} {{ user_form.username.errors }}</dir>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <table  align="center">
                        <tr>
                            <td>
                                {% load static %}
                                <img src="{% static 'img/lineaverde.png' %}" >
                            </td>
                        </tr>
                </table>
            </tr>
            <tr>
                <td>
                        <table>
                            <tr>
                                <td align="left">
                                   <div style="margin: 5px 0px 0px 110px;font-size:12px"> Actividad principal</dir>
                                </td>
                                <td align="left">
                                    <div style="margin: 5px 0px 0px 20px;font-size:12px;">Actividad secundaria</dir>
                                </td>
                                <td align="left">
                                    <div style="margin: 5px 0px 0px 20px;font-size:12px;">Dirección</dir>
                                </td>
                                <td align="left">
                                    <div style="margin: 5px 0px 0px 20px;font-size:12px;">CP</dir>
                                </td>
                            </tr>
                            <tr>
                                <td align="left">
                                    <div style="margin: 0px 0px 5px 110px;font-size:12px">{{ profile_form.actividadPrincipal }} {{ profile_form.actividadPrincipal.errors }}</dir>
                                </td >
                                <td align="left">
                                    <div style="margin: 0px 0px 5px 20px;font-size:12px;">{{ profile_form.actividadSecundaria }} {{ profile_form.actividadSecundaria.errors }}</dir>
                                </td>
                                <td align="left">
                                    <div style="margin: 0px 0px 5px 20px;font-size:12px;">{{ profile_form.direccion }} {{ profile_form.direccion.errors }}</dir>
                                </td>
                                <td align="left">
                                    <div style="margin: 0px 0px 5px 20px;font-size:12px;">{{ profile_form.cp }} {{ profile_form.cp.errors }}</dir>
                                </td>
                            </tr>
                        </table>
                </td>
            </tr>
            <tr>
                <td>
                    <table>
                        <tr>
                            <td align="left">
                                 <div style="margin: 5px 0px 0px 110px;font-size:12px">Provincia</dir>
                            </td>
                            <td align="left">
                                 <div style="margin: 5px 0px 0px 20px;font-size:12px;">Localidad de explotación</dir>
                            </td>
                            <td align="left">
                                 <div style="margin: 5px 0px 0px 20px;font-size:12px;">Comentarios adicionales sobre la empresa</dir>
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                               <div style="margin: 0px 0px 5px 110px;font-size:12px">{{ profile_form.provincia }} {{ profile_form.provincia.errors }}</dir>
                            </td >
                            <td align="left">
                               <div style="margin: 0px 0px 5px 20px;font-size:12px;">{{ profile_form.localidad }} {{ profile_form.localidad.errors }}</dir>
                            </td>
                            <td align="left">
                                <div style="margin: 0px 0px 5px 20px;font-size:12px;">{{ profile_form.comentarios }} {{ profile_form.comentarios.errors }}</dir>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <table  align="center">
                        <tr>
                            <td>
                                {% load static %}
                                <img src="{% static 'img/lineaverde.png' %}" >
                            </td>
                        </tr>
                </table>
            </tr>
            <tr>
                <td>
                        <table>
                            <tr>
                                <td align="left">
                                     <div style="margin: 5px 0px 0px 110px;font-size:12px">Usuario responsable <br>(Nombre y Apellido)</dir>
                                </td>
                                <td align="left" valign="bottom">
                                    <div style="margin: 5px 0px 0px 20px;font-size:12px;">Cargo</dir>
                                </td>
                                <td align="left" valign="bottom">
                                    <div style="margin: 5px 0px 0px 20px;font-size:12px;">Email</dir>
                                </td>
                                <td align="left" valign="bottom"    >
                                    <div style="margin: 5px 0px 0px 20px;font-size:12px;">Teléfono</dir>
                                </td>
                            </tr>
                            <tr>
                                <td align="left">
                                    <div style="margin: 0px 0px 5px 110px;font-size:12px">{{ profile_form.nombre }} {{ profile_form.nombre.errors }}</dir>
                                </td >
                                <td align="left">
                                    <div style="margin: 0px 0px 5px 20px;font-size:12px;">{{ profile_form.puesto }} {{ profile_form.puesto.errors }}</dir>
                                </td>
                                <td align="left">
                                    <div style="margin: 0px 0px 5px 20px;font-size:12px;">{{ profile_form.email }} {{ profile_form.email.errors }}</dir>
                                </td>
                                <td align="left">
                                    <div style="margin: 0px 0px 5px 20px;font-size:12px;">{{ profile_form.telefono }}{{ profile_form.telefono.errors }}</dir>
                                </td>
                            </tr>
                        </table>
                </td>
            </tr>
            <tr>
                <table align="center">
                        <tr>
                            <td>
                                {% load static %}
                                <img src="{% static 'img/lineaazul.png' %}" >
                            </td>
                        </tr>
                </table>
            </tr>
            <tr>
                <td>
                        <table>
                            <tr>
                                <td align="left">
                                    <div style="margin: 5px 0px 0px 310px;font-size:12px"> Contraseña</dir>
                                </td>
                                <td align="left">
                                    <div style="margin: 5px 0px 0px 20px;font-size:12px;">Confirmar contraseña</dir>
                                </td>
                            </tr>
                            <tr>
                                <td align="left">
                                    <div style="margin: 0px 0px 5px 310px;font-size:12px">{{ user_form.password1 }} {{ user_form.password1.errors }}</dir>
                                </td >
                                <td align="left">
                                    <div style="margin: 0px 0px 5px 20px;font-size:12px;">{{ user_form.password2 }} {{ user_form.password2.errors }}
                                </td>
                            </tr>
                        </table>
                </td>
            </tr>
            <tr>
                <td>
                    <table align="right">
                            <tr>
                                <td>
                                            Leí y acepto los <a href="{% url 'usuarios:condiciones' %}">términos y condiciones de privacidad</a>

                                                <input type="checkbox" id=100 name=terminos value=si  class="chkbox">

                                </td>
                                <td align="right">
                                    <input type="button" value="GUARDAR" class="boton15" onclick="javascript:Guardar();" style="margin: 0px 110px 0px 70px;"">
                                </td>
                            </tr>
                        </table>

                </td>
            </tr>
        </table>



</form>
</div>
{% endblock %}