apps/usuarios/urls.py
from django.conf.urls import url, include
from views import RegistroUsuario,UserHome, UserHomeErr, update_profile, Creditos, Creditos1, Simulador1,Simulador2,Simulador3,Simulador4,Simulador5,Simulador6,Simulador7, Metodologia,Metodologia1,Condiciones
from django.contrib.auth.decorators import login_required

urlpatterns = [
    #url(r'^registrar/', RegistroUsuario.as_view(), name="registrar"),
    url(r'^registrar/', RegistroUsuario, name="registrar"),
    url(r'^creditos/', Creditos, name="creditos"),
    url(r'^creditos1/', Creditos1, name="creditos1"),
    url(r'^$', login_required(UserHome), name="usuarios_home"),
    url(r'^(?P<errorMsg>\d+)/$', login_required(UserHomeErr), name="usuarios_home_err"),
    url(r'^misdatos/', login_required(update_profile), name="usuarios_datos"),
    url(r'^simulador/1/', Simulador1, name="simulador1"),
    url(r'^simulador/2/', Simulador2, name="simulador2"),
    url(r'^simulador/3/', Simulador3, name="simulador3"),
    url(r'^simulador/4/', Simulador4, name="simulador4"),
    url(r'^simulador/5/', Simulador5, name="simulador5"),
    url(r'^simulador/6/', Simulador6, name="simulador6"),
    url(r'^simulador/7/', Simulador7, name="simulador7"),
    url(r'^metodologia/', Metodologia, name="metodologia"),
    url(r'^metodologia1/', login_required(Metodologia1), name="metodologia1"),
    url(r'^condiciones/', Condiciones, name="condiciones"),
    ]

iarseapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login,password_reset,password_reset_done,password_reset_confirm,password_reset_complete, \
    logout_then_login
from django.contrib.auth.decorators import login_required
from apps.usuarios.views import UserHome


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^usuarios/', include('apps.usuarios.urls',namespace= "usuarios")),
    url(r'^survey/', include('apps.survey.urls',namespace= "surveys")),
    url(r'^reportes/', include('apps.reportes.urls',namespace= "reportes")),
    url(r'^indicadores/', include('apps.indicadores.urls',namespace= "indicadores")),
    url(r'^$', login_required(UserHome), name="land"),
    url(r'^accounts/login/', login,{'template_name':'usuarios/index.html'},name='login'),
    url(r'^logout/', logout_then_login,name="logout"),
    url(r'^reset/password_reset', password_reset,
        {'template_name':'usuarios/password_reset_fm.html',
        'email_template_name': 'usuarios/password_reset_email.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'usuarios/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'usuarios/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'usuarios/password_reset_complete.html'},
        name='password_reset_complete'),

]

apps/survey/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from ..usuarios.models import Provincia

class Encuesta(models.Model):
	name = models.CharField(max_length=400)
	description = models.TextField(blank=True, null=True,default=None)

	def __str__(self):
		return (self.name)

class Dimension(models.Model):
	name = models.CharField(max_length=400)
	description = models.TextField(blank=True, null=True, default=None)
	encuesta= models.ForeignKey(Encuesta, blank=True, null=True)

	def __str__(self):
		return (self.name)

class Survey(models.Model):
	class Meta:
		verbose_name = "Subtema"
		verbose_name_plural = "Subtemas"
	name = models.CharField(max_length=400)
	description = models.TextField(blank=True, null=True, default=None)
	completada = models.BooleanField(default=False)
	orden = models.IntegerField (null=True, default=1)
	dimension= models.ForeignKey(Dimension, blank=True, null=True)


	def __str__(self):
		return (self.name)

	def questions(self):
		if self.pk:
			return Question.objects.filter(survey=self.pk)
		else:
			return None

class Category(models.Model):
	class Meta:
		verbose_name = "Indicador"
		verbose_name_plural = "Indicadores"
	name = models.CharField(max_length=400)
	orden = models.IntegerField(null=True, default=1)
	survey = models.ForeignKey(Survey)

	def __str__(self):
		return (str(self.orden) + " - "+self.name)

def validate_list(value):
	'''takes a text value and verifies that there is at least one comma '''
	values = value.split(';')
	if len(values) < 2:
		raise ValidationError("The selected field requires an associated list of choices. Choices must contain more than one item.")

class Question(models.Model):
	class Meta:
		verbose_name = "Pregunta"
		verbose_name_plural = "Preguntas"
	TEXT = 'text'
	RADIO = 'radio'
	SELECT = 'select'
	SELECT_MULTIPLE = 'select-multiple'
	INTEGER = 'integer'

	QUESTION_TYPES = (
		(TEXT, 'text'),
		(RADIO, 'radio'),
		(SELECT, 'select'),
		(SELECT_MULTIPLE, 'Select Multiple'),
		(INTEGER, 'integer'),
	)

	text = models.TextField()
	required = models.BooleanField(default=True)
	category = models.ForeignKey(Category, blank=True, null=True, verbose_name="Indicador")
	survey = models.ForeignKey(Survey)
	question_type = models.CharField(max_length=200, choices=QUESTION_TYPES, default=RADIO)
	# the choices field is only used if the question type
	choices = models.TextField(blank=True, null=True,
		help_text='if the question type is "radio," "select," or "select multiple" provide a comma-separated list of options for this question .')

	def save(self, *args, **kwargs):
		if (self.question_type == Question.RADIO or self.question_type == Question.SELECT
			or self.question_type == Question.SELECT_MULTIPLE):
			validate_list(self.choices)
		super(Question, self).save(*args, **kwargs)

	def get_choices(self):
		''' parse the choices field and return a tuple formatted appropriately
		for the 'choices' argument of a form widget.'''
		choices = self.choices.split(';')
		choices_list = []
		for c in choices:
			c = c.strip()
			choices_list.append((c,c))
		choices_tuple = tuple(choices_list)
		return choices_tuple

	def __str__(self):
		return (self.text)

class ResponseMgr(models.Model):
	created = models.DateTimeField(auto_now_add=True)
	completada= models.BooleanField(default=False, blank=True)
	comentarios = models.TextField(blank=True, null=True)
	#organizacion = models.CharField(max_length=200,blank=True, null=True)
	#provincia = models.ForeignKey(Provincia, default=1, null=True)
	encuesta = models.ForeignKey(Encuesta, default=1)
	user = models.ForeignKey(User,default=1)

	def __str__(self):
		return ("Id = "+str(self.id)+" - "+self.encuesta.name +" - "+self.created.strftime('%Y-%m-%d'))

class Response(models.Model):
	# a response object is just a collection of questions and answers with a
	# unique interview uuid
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	completada = models.BooleanField(default=False, blank=True)
	survey = models.ForeignKey(Survey)
	#interviewer = models.CharField('Entrevistador', max_length=400, default='System')
	#interviewee = models.CharField('Entrevistado', max_length=400, default='System')
	#conditions = models.TextField('Condiciones durante la encuesta', blank=True, null=True)
	#comments = models.TextField('Comentarios', blank=True, null=True)
	interview_uuid = models.CharField('Identificador unico de encuesta', max_length=36)
	user = models.ForeignKey(User,default=1)
	respMgr = models.ForeignKey(ResponseMgr, default='', blank=True, null=True)

	def __str__(self):
		return ("response %s" % self.interview_uuid)

class AnswerBase(models.Model):
	question = models.ForeignKey(Question)
	response = models.ForeignKey(Response)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

# these type-specific answer models use a text field to allow for flexible
# field sizes depending on the actual question this answer corresponds to. any
# "required" attribute will be enforced by the form.
class AnswerText(AnswerBase):
	body = models.TextField(blank=True, null=True)

class AnswerRadio(AnswerBase):
	body = models.TextField(blank=True, null=True)

class AnswerSelect(AnswerBase):
	body = models.TextField(blank=True, null=True)

class AnswerSelectMultiple(AnswerBase):
	body = models.TextField(blank=True, null=True)

class AnswerInteger(AnswerBase):
	body = models.IntegerField(blank=True, null=True)

templates/simulador/1.html
{% extends 'base/base.html' %}

{% block content %}
{% load static %}
<div id="boxSimulador2">

<table>
        <tr>
						<table align="center">
							<tr>
								<td>
									<div style="font-size: 18px;margin: 10px 0 0 0;">Simulador</div>
								</td>
							</tr>
                		</table>
        </tr>
        <tr>
                            <table align="center">
                                <tr>
                                    <td>
                                        {% load static %}
                                        <img src="{% static 'img/lineaazul.png' %}" >
                                    </td>
                                </tr>
                            </table>
                        </tr>
        <tr>
        <td>
            {% load static %}
	   		<a href="{% url 'usuarios:simulador2' %}" ><img src="{% static 'img/basica.png' %}" style="margin: 30px 0px 20px 20px;"></a>
        </td>
        <td>{% load static %}
	   		<a href="{% url 'usuarios:simulador2' %}" ><img src="{% static 'img/amplia.png' %}" style="margin: 30px 0px 20px 20px;"></a>
        </td>
        <td>{% load static %}
	   		<a href="{% url 'usuarios:simulador2' %}" ><img src="{% static 'img/comprensiva.png' %}" style="margin: 30px 0px 20px 20px;"></a>
        </td>
    </tr>
</table>
</div>

{% endblock %}

templates/simulador/2.html
{% extends 'base/base.html' %}
{% block javascript %}


{% endblock %}
{% block content %}

    <div id="boxEncuestaIndex">
    <h1>Encuesta de indicadores</h1><br>

    <p>NOTA</p>
    <p>- Haga click en cada uno de los subtemas para comenzar a responder las preguntas asociadas a cada uno de ellos</p>
    <p>- Debe completar las respuestas de todos los subtemas e indicadores para finalizar la encuesta</p>
    </div>


    <div id="boxRegistro">

        <h2>VALORES - TRANSPARENCIA Y GESTIÓN</h2>
                        <a href="{% url 'usuarios:simulador3' %}">Visión y estrategia</a><br>
                        <a href="{% url 'usuarios:simulador3' %}">Relaciones transparentes con la sociedad</a><br>
                        <a href="{% url 'usuarios:simulador3' %}">Integración de la RS&amp;S a la estrategia del negocio</a><br>
        <h2>PRÁCTICAS DE EMPLEO Y TRABAJO DIGNO</h2>
                        <a href="{% url 'usuarios:simulador3' %}">Trabajo decente</a><br>
                        <a href="{% url 'usuarios:simulador3' %}">Salud y seguridad en el trabajo y calidad de vida</a><br>
                        <a href="{% url 'usuarios:simulador3' %}">Derechos humanos y respeto al individuo</a><br>
        <h2>SUSTENTABILIDAD DE LAS PRÁCTICAS AGRÍCOLAS - GANADERAS</h2>
                        <a href="{% url 'usuarios:simulador3' %}">Buenas prácticas agropecuarias  orientadas a la sustentabilidad</a><br>
                        <a href="{% url 'usuarios:simulador3' %}">Buenas prácticas ganaderas orientadas a la sustentabilidad</a><br>
                        <a href="{% url 'usuarios:simulador3' %}">Gerenciamiento del impacto ambiental</a><br>
        <h2>RELACIÓN CON CLIENTES Y OTROS PRODUCTORES</h2>
                        <a href="{% url 'usuarios:simulador3' %}">Salud y seguridad del consumidor</a><br>
        <form method="post" id="response">
        <input type='hidden' name='csrfmiddlewaretoken' value='1Cm46NbMR2GvyI5Nh8oUvXfgn1D3w5r0eC5bQp3mbqJ332HLNGWMZpxuOfNUAK6z' />
        <p><label for="id_comentarios">Comentario sobre el proceso de respuesta (opcional):</label> <textarea cols="40" id="id_comentarios" name="comentarios" rows="10">
</textarea></p>

    </form>
        <br><br>
        <input type="button" value="Terminar para obtener informe de autodiagnóstico" class="boton" onclick="window.location='{% url 'usuarios:simulador4' %}/';">
        <br>
    </div>
{% endblock %}

templates/simulador/4.html
{% extends 'base/base.html' %}
{% block javascript %}


{% endblock %}
{% block content %}


<div id="boxResultados4">
    <table>
        <tr>
            <table align="center">
                <tr>
                    <td>
                        <h2>Informe de Auto-diagnóstico en RS&S (Las notas aquí mostradas son a modo de ejemplo)</h2>
                    </td>
                </tr>
            </table>
        </tr>
        <tr>
                <table align="center">
                        <tr>
                            <td>
                                {% load static %}
                                <img src="{% static 'img/lineaazul.png' %}" >
                            </td>
                        </tr>
                </table>
            </tr>
            <tr>
                <table align="center">
                        <tr>
                            <td>
                                <input type="button" value="EXPORTAR A PDF" class="boton19" onclick="javascript:CreaPDF();" style="margin: 10px 10px 10px 10px;">
                            </td>
                            <td>
                                <input type="button" value="VER RESPUESTAS" class="boton20" onclick="javascript:CreaPDF();" style="margin: 10px 10px 10px 10px;">
                            </td>
                        </tr>
                </table>

            </tr>
            <tr>
                <table style="margin: 0px 0px 0px 120px">
                        <tr>
                            <td>
                                <p>NOTA</p>
                                <p>Posicione el cursor del mouse sobre cada dimensión/subtema para ver la nota del gráfico </p>
                                <p>Nota de Desempeño General: 6.48</p>
                            </td>
                        </tr>
                </table>
            </tr>
            <tr>
                <table align="center">
                        <tr>
                            <td>
                                {% load static %}
                                <img src="{% static 'img/lineaazul.png' %}" >
                            </td>
                        </tr>
                </table>
            </tr>
            <tr>
                <table align="center">
                        <tr>
                            <td>
                                {% load static %}
                                <img src="{% static 'img/graficosimulador1.png' %}">
                            </td>
                        </tr>
                </table>
            </tr>
            <tr>
                <table align="center">
                        <tr>
                            <td>
                                {% load static %}
                                <img src="{% static 'img/lineaazul.png' %}" >
                            </td>
                        </tr>
                </table>
            </tr>
    </table>
    
<table align="center">
    <tr>
        <td VALIGN=TOP>
            <table>
                <tr>
                    <td>

            <h3>INDICADORES</h3>
            <div class="datagrid">
			<table>
				<thead>
					<tr>
						<th>Nombre</th>
						<th>Nota</th>
					</tr>
				</thead>
				<tbody>



                    <tr>
                        <td> 1- Misión - Visión - Valores </td><td> 10.00</td>
                    </tr>



                    <tr>
                        <td> 1- Prácticas Anticorrupción y Anticoima </td><td> 10.00</td>
                    </tr>



                    <tr>
                        <td> 1- Mapeo de los Impactos de la Operación y Gestión de Riesgos </td><td> 10.00</td>
                    </tr>



                    <tr>
                        <td> 1- Relaciones con Trabajadores Propios </td><td> 10.00</td>
                    </tr>



                    <tr>
                        <td> 1- Relaciones con Trabajadores tercerizados / subcontratados / estacionales </td><td> 10.00</td>
                    </tr>



                    <tr>
                        <td> 1- Política de Remuneración, Prestaciones y Carrera </td><td> 10.00</td>
                    </tr>



                    <tr>
                        <td> 1- Cuidados de Salud, Seguridad y Condiciones de Trabajo </td><td> 10.00</td>
                    </tr>



                    <tr>
                        <td> 1- Condiciones de Trabajo, Calidad de Vida y Jornada Laboral </td><td> 10.00</td>
                    </tr>



                    <tr>
                        <td> 1- Compromiso con el Futuro de los Niños </td><td> 10.00</td>
                    </tr>



                    <tr>
                        <td> 1- Compromiso con la Equidad y la No Discriminación Racial o por Origen Nacional (Xenofobia) </td><td> 10.00</td>
                    </tr>



                    <tr>
                        <td> 1- Uso Sustentable de los Recursos: Suelo </td><td> 10.00</td>
                    </tr>



                    <tr>
                        <td> 1- Uso Sustentable y Seguro de Insumos de síntesis química y natural. </td><td> 10.00</td>
                    </tr>



                    <tr>
                        <td> 1- Uso sustentable de la Biodiversidad y Restauración de Hábitats Naturales: Bosques Nativos (Ley de Bosques) </td><td> 10.00</td>
                    </tr>



                    <tr>
                        <td> 1- Cuidado de la Inocuidad de los Alimentos y de las Prácticas Productivas que podrían afectarlos. </td><td> 10.00</td>
                    </tr>






































                </tbody>
            </table>
            </div>
            </td>
                </tr>
            </table>
        </td>
        </tr>
        <tr>        
        <td VALIGN=TOP>
            <table>
                <tr><td VALIGN=TOP>
                    <table ><tr><td VALIGN=TOP>
                    <h3>TEMAS</h3>
                        <div class="datagrid">
                        <table>
                            <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Nota</th>
                                </tr>
                            </thead>
                            <tbody>







































                                <tr>
                                    <td> Visión y estrategia </td><td> 10.00</td>
                                </tr>



                                <tr>
                                    <td> Relaciones transparentes con la sociedad </td><td> 10.00</td>
                                </tr>



                                <tr>
                                    <td> Integración de la RSyS a la estrategia del negocio </td><td> 10.00</td>
                                </tr>



                                <tr>
                                    <td> Trabajo decente </td><td> 10.00</td>
                                </tr>



                                <tr>
                                    <td> Salud y seguridad en el trabajo y calidad de vida </td><td> 10.00</td>
                                </tr>



                                <tr>
                                    <td> Derechos humanos y respeto al individuo </td><td> 10.00</td>
                                </tr>



                                <tr>
                                    <td> Buenas prácticas agropecuarias </td><td> 10.00</td>
                                </tr>



                                <tr>
                                    <td> Gerenciamiento del impacto ambiental </td><td> 10.00</td>
                                </tr>



                                <tr>
                                    <td> Salud y seguridad del consumidor </td><td> 10.00</td>
                                </tr>












                            </tbody>
                        </table>
                            </div>
                    </td>
                    <td>
                        <h3>DIMENSIONES</h3>
                        <div class="datagrid">
            <table>
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Nota</th>
                    </tr>
                </thead>
                <tbody>

























































                    <tr>
                        <td> Valores, transparencia y gestión </td><td> 10.00</td>
                    </tr>



                    <tr>
                        <td> Prácticas de empleo y trabajo digno </td><td> 10.00</td>
                    </tr>



                    <tr>
                        <td> Sustentabilidad de las prácticas agrícolas - ganaderas </td><td> 10.00</td>
                    </tr>



                    <tr>
                        <td> Relaciones con clientes y otros productores </td><td> 10.00</td>
                    </tr>




                </tbody>
            </table>
            </div>
            <h3>DISTRIBUCIÓN POR ESTADÍOS</h3>
                <table>
                    <tr>
                        <td>

                        <div class="datagrid">
                        <table>
                            <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Cantidad</th>
                                </tr>
                            </thead>
                            <tbody>































                                <tr>
                                    <td> Estadío 1 </td><td> 0.00</td>
                                </tr>




                                <tr>
                                    <td> Estadío 2 </td><td> 0.00</td>
                                </tr>




                                <tr>
                                    <td> Estadío 3 </td><td> 0.00</td>
                                </tr>




                                <tr>
                                    <td> Estadío 4 </td><td> 14.00</td>
                                </tr>































                                <tr>
                                    <td> No se identifica con algún estadío:</td> <td>1.00</td>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        </div>
                        </td>
                    </tr>
                </table>
                            </td></tr>
                        </table>
                    </td></tr>
                    </table>
                    </td>
                    </tr>
                    </table>

                </td></tr>
                    
</div>



	<div id="push"></div> <!-- #push goes inside container -->
	</div> <!-- /container -->

	<footer class="footer">
		<div class="container">


		</div>
	</footer>
	<!-- Le javascript -->



  </body>
</html>

{% endblock %}