apps/indicadores/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from django.contrib import admin
from views import Resultados, Respuestas, ResultadosComp,ConsultaConsolidada,ResultadosConsolidados, Graficos, GraficosComp, Indicadores

urlpatterns = [
    url(r'^resultados/(?P<id>\d+)/$', login_required(Resultados), name='resultados'),
    url(r'^resultadoscomp/(?P<id>\d+)/$', login_required(ResultadosComp), name='resultadoscomp'),
    url(r'^respuestas/(?P<id>\d+)/$', login_required(Respuestas), name='respuestas'),
    url(r'^consultaconsolidada/$', login_required(ConsultaConsolidada), name='consultaconsolidada'),
    url(r'^resultadosconsolidados/$', login_required(ResultadosConsolidados), name='resultadosconsolidados'),
    url(r'^graficos/(?P<id>\d+)/$', Graficos, name='graficos'),
    url(r'^graficoscomp/(?P<id>\d+)/$', GraficosComp, name='graficoscomp'),
    url(r'^indicadores/(?P<id>\d+)/$', login_required(Indicadores), name='indicadores'),
]

apps/survey/urls.py
from django.conf.urls import include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf import settings
from views import Index, SurveyDetail, Confirm, privacy,EncuestaIndex,EncuestaIndexView, SubtemaView, ResponseDelete, EncuestaTerminar
from django.views.static import serve
from django.contrib.auth.decorators import login_required

admin.autodiscover()
media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')

urlpatterns = [
	# Examples:
	url(r'^$', login_required(Index), name='home'),
	url(r'^(?P<idr>\d+)/(?P<ids>\d+)/$', login_required(SurveyDetail), name='survey_detail'),
	url(r'^subtema/(?P<idr>\d+)/(?P<ids>\d+)/$', login_required(SubtemaView), name='survey_subtema'),
	url(r'^encuesta/(?P<id>\d+)/$', login_required(EncuestaIndex), name='encuesta_completa'),
	url(r'^encuesta_terminar/(?P<id>\d+)/$', login_required(EncuestaTerminar), name='encuesta_terminar'),
	url(r'^encuesta_view/(?P<id>\d+)/(?P<errorMsg>\d+)/(?P<slide>\d+)/$', login_required(EncuestaIndexView), name='encuesta_view'),
	url(r'^encuesta_delete/(?P<id>\d+)/$', login_required(ResponseDelete), name='encuesta_delete'),
	url(r'^confirm/(?P<uuid>\w+)/$', login_required(Confirm), name='confirmation'),
	url(r'^privacy/$', login_required(privacy), name='privacy_statement'),


	# Uncomment the admin/doc line below to enable admin documentation:
	#url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	# Uncomment the next line to enable the admin:
	#url(r'^admin/', include(admin.site.urls)),

    url (r'^%s/(?P<path>.*)$' % media_url, login_required(serve),
     { 'document_root': settings.MEDIA_ROOT, 'show_indexes':True }),
]

apps/usuarios/urls.py
from django.conf.urls import url, include
from views import RegistroUsuario,UserHome, UserHomeErr, update_profile, Creditos, Creditos1, Simulador1,Simulador2,Simulador3,Simulador4,Simulador5,Simulador6,Simulador7, Metodologia,Metodologia1,Condiciones
from django.contrib.auth.decorators import login_required

urlpatterns = [
    #url(r'^registrar/', RegistroUsuario.as_view(), name="registrar"),
    url(r'^registrar/', RegistroUsuario, name="registrar"),
    url(r'^creditos/', Creditos, name="creditos"),
    url(r'^creditos1/', Creditos1, name="creditos1"),
    url(r'^$', login_required(UserHome), name="usuarios_home"),
    url(r'^(?P<errorMsg>\d+)/$', login_required(UserHomeErr), name="usuarios_home_err"),
    url(r'^misdatos/', login_required(update_profile), name="usuarios_datos"),
    url(r'^simulador/1/', Simulador1, name="simulador1"),
    url(r'^simulador/2/', Simulador2, name="simulador2"),
    url(r'^simulador/3/', Simulador3, name="simulador3"),
    url(r'^simulador/4/', Simulador4, name="simulador4"),
    url(r'^simulador/5/', Simulador5, name="simulador5"),
    url(r'^simulador/6/', Simulador6, name="simulador6"),
    url(r'^simulador/7/', Simulador7, name="simulador7"),
    url(r'^metodologia/', Metodologia, name="metodologia"),
    url(r'^metodologia1/', login_required(Metodologia1), name="metodologia1"),
    url(r'^condiciones/', Condiciones, name="condiciones"),
    ]

iarseapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login,password_reset,password_reset_done,password_reset_confirm,password_reset_complete, \
    logout_then_login
from django.contrib.auth.decorators import login_required
from apps.usuarios.views import UserHome


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^usuarios/', include('apps.usuarios.urls',namespace= "usuarios")),
    url(r'^survey/', include('apps.survey.urls',namespace= "surveys")),
    url(r'^reportes/', include('apps.reportes.urls',namespace= "reportes")),
    url(r'^indicadores/', include('apps.indicadores.urls',namespace= "indicadores")),
    url(r'^$', login_required(UserHome), name="land"),
    url(r'^accounts/login/', login,{'template_name':'usuarios/index.html'},name='login'),
    url(r'^logout/', logout_then_login,name="logout"),
    url(r'^reset/password_reset', password_reset,
        {'template_name':'usuarios/password_reset_fm.html',
        'email_template_name': 'usuarios/password_reset_email.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'usuarios/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'usuarios/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'usuarios/password_reset_complete.html'},
        name='password_reset_complete'),

]

apps/indicadores/models.py
from __future__ import unicode_literals
from django.db import models
from ..usuarios.models import Provincia
from ..survey.models import ResponseMgr
from django.contrib.auth.models import User

class TipoIndicador(models.Model):
	name = models.CharField(max_length=400)
	description = models.TextField(blank=True, null=True,default=None)

	def __str__(self):
		return (self.name)

class Evaluacion(models.Model):
    fecha = models.DateTimeField(auto_now_add=True)
    ubicacion = models.ForeignKey(Provincia)
    rspMgr = models.ForeignKey(ResponseMgr)
    usuario = models.ForeignKey(User)

    def __str__(self):
        return (str(self.fecha))

class Indicador(models.Model):
    name = models.CharField(max_length=400)
    orden = models.IntegerField(null=True, default=1)
    tipo = models.ForeignKey(TipoIndicador)

    def __str__(self):
        return (self.name)

class Nota (models.Model):
    nota = models.FloatField()
    orden = models.IntegerField(null=True, default=1)
    indicador = models.ForeignKey(Indicador)
    evaluacion = models.ForeignKey(Evaluacion)

    def __str__(self):
        #return (str(self.nota)+" - "+self.indicador.name)
        return (str("%0.2f" % self.nota))

apps/indicadores/views.py
from django.shortcuts import render
from models import Evaluacion,Indicador,Nota,TipoIndicador,Provincia
from ..survey.models import ResponseMgr,Response,AnswerRadio,Dimension,Survey,Encuesta, Category, AnswerText
from ..usuarios.models import Profile
from django.contrib.auth.models import User, Group
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import redirect
import os
import selenium
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import time
import base64
import random

# Create your views here.

def Resultados(request, id):
    evaluacion= Evaluacion.objects.get(id=id)
    perfiles = Profile.objects.all()

    for p in perfiles:
        if (p.user==evaluacion.usuario):
            perfil=p

    # Cargo los indicadores de la encuesta para saber cuantos son para el calculo de estadio que no se identifiquen
    dimensiones = Dimension.objects.filter(encuesta=evaluacion.rspMgr.encuesta)
    temas=[]
    indicadores=[]

    for dim in dimensiones:
        temDim = Survey.objects.filter(dimension=dim)
        for t in temDim:
            temas.append(t)

    for tem in temas:
        indica = Category.objects.filter(survey=tem)
        for ind in indica:
            indicadores.append(ind)

    cantInd= len(indicadores)

    notas= Nota.objects.filter(evaluacion=evaluacion).order_by("orden")

    estadio1 = 0
    estadio2 = 0
    estadio3 = 0
    estadio4 = 0
    totalEst = 0
    for nota in notas:
        if (nota.indicador.id==77):
            estadio1=nota
            totalEst = totalEst+ nota.nota
           # print estadio1
        if (nota.indicador.id == 78):
            estadio2 = nota
            totalEst = totalEst + nota.nota
            #print estadio2
        if (nota.indicador.id==79):
            estadio3=nota
            totalEst = totalEst + nota.nota
            #print estadio3
        if (nota.indicador.id==80):
            estadio4=nota
            totalEst = totalEst + nota.nota
            #print estadio4
    estadioNo= cantInd-totalEst

    sitio=get_current_site(request)
    print sitio

    dcap = dict(DesiredCapabilities.PHANTOMJS)
    dcap["phantomjs.page.settings.userAgent"] = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36")
    driver = webdriver.PhantomJS(desired_capabilities=dcap, service_args=['--ignore-ssl-errors=true', '--ssl-protocol=any', '--web-security=false'])
    driver.set_window_size(1024, 768)   
    #urlcaptura='http://www.lavoz.com.ar'
    #urlcaptura='http://indicagro.bccba.com.ar/indicadores/graficos/'+str(evaluacion.id)
    #urlcaptura='https://192.168.100.217/indicadores/graficos/'+str(evaluacion.id)
    urlcaptura= str(sitio)+'/indicadores/graficos/'+str(evaluacion.id)
    driver.get(urlcaptura)
    time.sleep(2)
    driver.execute_script('document.body.style.background = "white"')
    driver.save_screenshot('./static/graficos/'+str(evaluacion.id)+'.png')
    driver.quit()

    with open('./static/graficos/'+str(evaluacion.id)+'.png', "rb") as imageFile:
        imagen = base64.b64encode(imageFile.read())
        #print cadena

    with open('./static/img/logobolsa.png', "rb") as imageFile:
        imagen1 = base64.b64encode(imageFile.read())

    with open('./static/img/indicadores2.png', "rb") as imageFile:
        imagen2 = base64.b64encode(imageFile.read())

    with open('./static/img/logoiarse.png', "rb") as imageFile:
        imagen3 = base64.b64encode(imageFile.read())

    contexto = {
                'evaluacion':evaluacion,
                'notas':notas,
                'estadio1':estadio1,
                'estadio2': estadio2,
                'estadio3': estadio3,
                'estadio4': estadio4,
                'imagen':imagen,
                'imagen1':imagen1,
                'imagen2': imagen2,
                'imagen3': imagen3,
                'perfil':perfil,
                'estadioNo':str("%0.2f" % estadioNo)
                }
    return render(request, 'resultados1.html', contexto)

def Respuestas(request, id):
    rspMgr=ResponseMgr.objects.get(id=id)
    encuesta= Encuesta.objects.get(id=rspMgr.encuesta.id)
    profile= Profile.objects.get(user=rspMgr.user)
    indicadores = []
    # Levanto los responses (uno para cada subtema)
    responses = Response.objects.filter(respMgr=rspMgr)

    # Aca se van a almacenar todas las respuestas (para no tene que levantarlas para cada indicador
    todasRespuestas = []

    # Levanto las respuestas de la evaluacion
    for indx, res in enumerate(responses):
        resps = AnswerRadio.objects.filter(response=res)
        respsTxt = AnswerText.objects.filter(response=res)
        for r in resps:
            todasRespuestas.append(r)
        for r in respsTxt:
            todasRespuestas.append(r)
        indi = Category.objects.filter(survey=res.survey)
        for ind in indi:
            indicadores.append(ind)
    todasRespuestas.sort(key=lambda todasRespuestas:todasRespuestas.question.text)
    indicadores.sort(key=lambda indicadores:indicadores.orden)
    contexto = {
                'rspMgr':rspMgr,
                'profile':profile,
                'encuesta':encuesta,
                'responses':responses,
                'indicadores':indicadores,
                'todasRespuestas':todasRespuestas
                }
    return render(request, 'respuestas.html', contexto)

def ResultadosComp(request, id):
    user= User.objects.get(id=id)
    perfiles = Profile.objects.all()

    for p in perfiles:
        if (p.user==user):
            perfil=p
    evaluaciones= Evaluacion.objects.filter(usuario=user).order_by('-fecha')

    if (len(evaluaciones) <= 1):
        messages.error(request, 'Para hacer la consulta comparativa debe haber realizado al menos, dos auto-evaluaciones')
        return redirect('usuarios:usuarios_home')



    for indx, ev in enumerate(evaluaciones):
        if(indx==0):
            evaluacion = ev

            # Cargo los indicadores de la encuesta para saber cuantos son para el calculo de estadio que no se identifiquen
            dimensiones = Dimension.objects.filter(encuesta=ev.rspMgr.encuesta)
            temas = []
            indicadores = []

            for dim in dimensiones:
                temDim = Survey.objects.filter(dimension=dim)
                for t in temDim:
                    temas.append(t)

            for tem in temas:
                indica = Category.objects.filter(survey=tem)
                for ind in indica:
                    indicadores.append(ind)

            cantInd = len(indicadores)

            notas = Nota.objects.filter(evaluacion=ev).order_by("orden")
            estadio1 = 0
            estadio2 = 0
            estadio3 = 0
            estadio4 = 0
            suma1=0
            for nota in notas:
                if (nota.indicador.id==77):
                    estadio1=nota
                    suma1=suma1+nota.nota
                if (nota.indicador.id == 78):
                    estadio2 = nota
                    suma1 = suma1 + nota.nota
                if (nota.indicador.id==79):
                    estadio3=nota
                    suma1 = suma1 + nota.nota
                if (nota.indicador.id==80):
                    estadio4=nota
                    suma1 = suma1 + nota.nota
            estadioNo1 = cantInd - suma1

        if (indx == 1):
            evaluacion1 = ev

            # Cargo los indicadores de la encuesta para saber cuantos son para el calculo de estadio que no se identifiquen
            dimensiones = Dimension.objects.filter(encuesta=ev.rspMgr.encuesta)
            temas = []
            indicadores = []

            for dim in dimensiones:
                temDim = Survey.objects.filter(dimension=dim)
                for t in temDim:
                    temas.append(t)

            for tem in temas:
                indica = Category.objects.filter(survey=tem)
                for ind in indica:
                    indicadores.append(ind)

            cantInd = len(indicadores)

            notas1 = Nota.objects.filter(evaluacion=ev).order_by("orden")
            estadio11 = 0
            estadio21 = 0
            estadio31 = 0
            estadio41 = 0
            suma2 = 0

            for nota in notas1:
                if (nota.indicador.id == 77):
                    estadio11 = nota
                    suma2 = suma2 + nota.nota
                if (nota.indicador.id == 78):
                    estadio21 = nota
                    suma2 = suma2 + nota.nota
                if (nota.indicador.id == 79):
                    estadio31 = nota
                    suma2 = suma2 + nota.nota
                if (nota.indicador.id == 80):
                    estadio41 = nota
                    suma2 = suma2 + nota.nota
            estadioNo2 = cantInd - suma1

    tipoIndicador= TipoIndicador.objects.get(id=2)
    dimensiones= Indicador.objects.filter(tipo=tipoIndicador)
    notasDim= []
    notasDim1 = []

    for dim in dimensiones:
        band=False
        for nota in notas:
            if(dim.id ==nota.indicador.id):
                notasDim.append(nota)
                band=True
        if(band==False):
            notaVacia = Nota()
            notaVacia.indicador = dim
            notaVacia.nota = 0
            notasDim.append(notaVacia)
        band = False
        for nota in notas1:
            if (dim.id == nota.indicador.id):
                notasDim1.append(nota)
                band = True
        if (band == False):
            notaVacia = Nota()
            notaVacia.indicador = tem
            notaVacia.nota = 0
            notasDim1.append(notaVacia)

    tipoIndicador= TipoIndicador.objects.get(id=4)
    temas= Indicador.objects.filter(tipo=tipoIndicador)
    notasTem= []
    notasTem1 = []

    for tem in temas:

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
	<meta charset="utf-8">
	<title>INDICAGRO</title>
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
	   {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}">
	  {% block javascript %}

	  {% endblock %}

  </head>
{% load static %}

  <body>
  	<div class="boxCenterNav">
	<nav>
	 <ul class="fullnav">
		 <table align="center">
			 <tr>


	  <td><li>
		  {% load static %}
	   		<a href="{% url 'usuarios:usuarios_home' %}" ><img src="{% static 'img/indicadores2.png' %}" width="282px" height="145px"></a>
	  </li>
	 </td>
	  <td align="right"><li>
		  <a href="#" class="boton16">¡ COMENZAR ENCUESTA !</a>
	   <ul>
		   <table align="center">
			   <tr>
				   <td>
						<li>
						 <a href="{% url 'surveys:encuesta_completa' 2 %}"  title="Nivel Básico: Contempla un total de 15 indicadores para una auto evaluación elemental en materia de RS&S. Se recomienda para una pequeña empresa." >NIVEL BÁSICO - </a>
						</li>
				   </td>
					<td>
						<li>
						 <a href="{% url 'surveys:encuesta_completa' 3 %}" title="Nivel Amplio: Contempla un total de 30 indicadores para una autoevaluación en materia de RS&S. Se recomienda para una mediana empresa.">NIVEL AMPLIO - </a>
						</li>
				   </td>
				   <td>
						<li>
						 <a href="{% url 'surveys:encuesta_completa' 1 %}" title="Nivel Comprensivo: Contempla un total de 50 indicadores para una autoevaluación exhaustiva en materia de RS&S. Se recomienda para una gran empresa.">NIVEL COMPRENSIVO</a>
						</li>
			   </td>
			   </tr>
		   </table>
	   </ul>
	  </li>
	 </td>

		 <td>
			 <table>
				 <tr>
					 <td>
						 <li>
							 <a href="{% url 'usuarios:metodologia1' %}" class="boton17" >GUÍA DE USO</a>
						</li>
					 </td>
				 </tr>
				 <tr>
					 <td>
							 <li>
						   <a href="#" class="boton17">CONSULTAR INDICADORES</a>
						   <ul>
							   <table align="center">
								   <tr>
									   <td>
											<li>
												<a href="{% url 'indicadores:indicadores' 2 %}">NIVEL BÁSICO - </a>

											</li>
									   </td>
									<td>
										<li>
											<a href="{% url 'indicadores:indicadores' 3 %}">NIVEL AMPLIO - </a>
										</li>
								   </td>
									<td>
										<li>
											 <a href="{% url 'indicadores:indicadores' 1 %}">NIVEL COMPRENSIVO</a>
										</li>
								   </td>
								   </tr>
							   </table>
						   </ul>
						  </li>
					 </td>
				 </tr>
			 </table>

		 </td>

		 <td>
			 <table>
				 <tr>
					 <td>
						 <li >
							<a href="{% url 'usuarios:creditos1' %}" class="boton17">CRÉDITOS</a>
						 </li>
					 </td>
				 </tr>
				 <tr>
					 <td>
						 <li>
							<a href="{% url 'usuarios:usuarios_datos' %}" class="boton18"> {{ request.user.profile.empresa }} </a>
						 </li>
					 </td>
				 </tr>
			 </table>

			</td>
				 <td>
			 <table>
				 <tr>
					 <td>
						 <li >
							<a href="{% static 'download/libro-indicadores.pdf' %}" class="boton18">DESCARGAR LIBRO</a>
						 </li>
					 </td>
				 </tr>
				 <tr>
					 <td>
						 <li>
							<a href="{% url 'logout' %}" class="boton18">SALIR</a>
						 </li>
					 </td>
				 </tr>
			 </table>

			</td>
	 	{% if request.user.is_superuser %}
		 	<td><li>
			   <a href="#" class="boton16">ADMIN</a>
			   <ul>
					<li>
				 		<a href="{% url 'indicadores:consultaconsolidada' %}" > CONSULTA CONSOLIDADA </a>
					</li>
				</ul>
		 	</li>
		 	</td>
	 	{% endif %}
	 </tr>
		 </table>
	 </ul>

	</nav>
	</div>



	<div class="boxCenter">
		
	{% block body %}
	{% endblock %}

	<div id="push"></div> <!-- #push goes inside container -->
	</div> <!-- /container -->
	<!-- Le javascript -->

	{% block extrajs %}
	{% endblock %}
      {% block footer %}
<div id="boxFooter">

        <table>
            <tr>
                <td>
                            {% load static %}
                            <img src="{% static 'img/logobolsafoot.png' %}" width="185" height="65" style="margin:  0px 0px 0px 40px">
                </td>
                <td>
                <td align="left">
                            {% load static %}
                            <a href="https://www.google.com.ar/maps/place/Bolsa+y+C%C3%A1mara+de+Cereales+de+C%C/3%B3rdoba/@-31.4162746,-64.1774003,15z/data=!4m5!3m4!1s0x0:0xbf6fb57f3a4ae187!8m2!3d-31.4144515!4d-64.173739"><img src="{% static 'img/11.png' %}" width="35px" height="39px" style="margin:  0px 10px 0px 10px;"></a>
                </td>
                <td align="left">
                            {% load static %}
                            <a href="mailto:indicagro@bccba.org.ar"> <img src="{% static 'img/12.png' %}" width="60px" height="30px"></a>
                </td>
                <td align="left">
                            {% load static %}
                            <a href="https://twitter.com/BCCBA"> <img src="{% static 'img/13.png' %}" width="60px" height="30px"></a>
                </td>
                <td align="left">
                            {% load static %}
                            <a href="https://www.facebook.com/bccba.bolsadecerealesdecordoba"><img src="{% static 'img/14.png' %}" width="60px" height="30px"></a>
                </td>


                <td>
                            {% load static %}
                            <img src="{% static 'img/logoiarse.png' %}" width="148" height="114" style="margin:  0px 0px 0px 50px">
                </td>

                <td>
                    {% load static %}
                    <a href="https://www.google.com.ar/maps/place/Almte+Guillermo+Brown+245,+X5002IWE+C%C3%B3rdoba/@-31.4078076,-64.2212375,17z/data=!4m13!1m7!3m6!1s0x943298bd67311b89:0xb55bfb56b1ae8409!2sAlmte+Guillermo+Brown+245,+X5002IWE+C%C3%B3rdoba!3b1!8m2!3d-31.4078076!4d-64.2190488!3m4!1s0x943298bd67311b89:0xb55bfb56b1ae8409!8m2!3d-31.4078076!4d-64.2190488"><img src="{% static 'img/21.png' %}" width="35px" height="39px" style="margin:  0px 10px 0px 10px;"></a>
                </td>
                <td>
                    {% load static %}
                    <a href="mailto:mail@iarse.org"> <img src="{% static 'img/22.png' %}" width="60px" height="30px"></a>
                </td>
                <td>
                    {% load static %}
                    <a href="https://twitter.com/iarse?lang=es"><img src="{% static 'img/23.png' %}" width="60px" height="30px"></a>
                </td>
                <td>
                    {% load static %}
                    <a href="https://www.facebook.com/IARSE/"><img src="{% static 'img/24.png' %}" width="60px" height="30px"></a>
                </td>


            </tr>

    </table>



</div>
    {% endblock %}
  </body>
</html>

templates/home.html
{% extends 'index.html' %}

templates/indicadores.html
{% extends 'base.html' %}

{% block body %}
<div id="boxRegistro">
<h3>Encuesta {{ encuesta.name }}</h3>
</div>

<div id="boxResultados">

    <table>
        {% for ind in indicadores %}
        <tr>
            <td>{{ ind }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}